name: "Turma TSI14"
description: "Site Oficial da Turma de Tecnologia em Sistemas para Internet - IFC"
baseurl: /turmatsi14
destination: ./_site
paginate: 10
permalink: /:month/:day/:year/:categories/:title

